project:
  type: website
  output-dir: docs

website:
  title: "EcoViz+AI"
  navbar:
    right:
      - about.qmd
      - resources.qmd
      - people.qmd
      - modelzoo.qmd
      - communities.qmd
      #- pubs.qmd
      #- research.qmd
  favicon: media/logos/EcoVizAI_Logo3_small.png

format:
  html:
    theme:
      - custom.scss
    mainfont: Nunito
    css: styles.css
    toc: true
    page-layout: full

editor: visual
